cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'Homebrew/bundle'
tap 'd12frosted/emacs-plus'

brew 'coreutils'
brew 'zsh'
brew 'wget'
brew 'libgit2'
brew 'emacs-plus'
brew 'pyenv'

# brew 'go'
# brew 'imagemagick'
# brew 'jp2a'
# brew 'libcaca', args: ['with-imlib2']
# brew 'openssl'
# brew 'node'
# brew 'readline'
# brew 'postgresql'
# brew 'ruby-build'
# brew 'rbenv'
# brew 'roundup'
# brew 'spaceman-diff'
# brew 'spark'
# brew 'unrar'
# brew 'youtube-dl'

# cask '1password'
# cask 'adium'
# cask 'atom'
# cask 'firefox'
# cask 'garmin-express'
# cask 'google-chrome'
# cask 'handbrake'
# cask 'mapbox-studio'
# cask 'seashore'
# cask 'slack'
# cask 'steam'
# cask 'transmission'
# cask 'tunnelbear'
# cask 'vlc'
